# Generated by Django 3.0.3 on 2020-03-26 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grp', '0021_auto_20200324_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cicle',
            options={'ordering': ['last_cicle_first_date']},
        ),
    ]
