# Generated by Django 3.0.3 on 2020-03-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grp', '0023_cicle_maximum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cicle',
            name='maximum',
        ),
    ]
